### ISSUE TITLE
도서 상세 정보 표시 기능

### ISSUE THREAD

**Issue by Kuu1208** [Kuu1208/capstone_frontend#5]
사용자가 요구하는 도서 데이터가 서버에 존재할 시, 해당 도서 이미지 혹은 제목을 클릭하면 해당 도서의 페이지로 넘어간다. 도서의 제목이나 작가, isbn, 가격, 간략한 줄거리 소개 등의 상세정보를 제공한다.

<img width="470" alt="image" src="https://github.com/Kuu1208/capstone_frontend/assets/130426876/ca3a2959-4a40-40bb-bfd9-07a279b68e44">

**Comment by pilsungk-oss** [comment]
구현을 완료하고 이슈를 close 할 때, 해당 코드를 커밋하고 이를 PR로 처리하면서 PR과 이슈를 연결할 수 있으니 이를 이용하면 좋습니다.
아래 글을 한번 살펴보기 바랍니다.  
https://bumkeyy.gitbook.io/bumkeyy-code/project-management/pull-request
